In [2]:
import pandas as pd
import bamboolib as bam

In [5]:
df = pd.read_excel('2010-2018-faculty-by-country-of-nationality.xlsx')

In [7]:
df

          year       Nationality  Faculty
0    Fall 2010           Algeria      1.0
1    Fall 2010           Armenia      NaN
2    Fall 2010         Australia     36.0
3    Fall 2010           Austria      NaN
4    Fall 2010           Bahrain      NaN
5    Fall 2010        Bangladesh      1.0
6    Fall 2010           Belgium      1.0
7    Fall 2010            Brazil      NaN
8    Fall 2010  British Ind. O T      NaN
9    Fall 2010          Bulgaria      1.0
10   Fall 2010            Canada     54.0
11   Fall 2010             China      3.0
12   Fall 2010          Colombia      1.0
13   Fall 2010           Croatia      NaN
14   Fall 2010            Cyprus      NaN
15   Fall 2010           Denmark      2.0
16   Fall 2010             Egypt     22.0
17   Fall 2010          Ethiopia      NaN
18   Fall 2010            France      3.0
19   Fall 2010     French Guiana      1.0
20   Fall 2010           Germany      5.0
21   Fall 2010             Ghana      NaN
22   Fall 2010            Greece      1.0
23   Fall 2010            Guyana      NaN
24   Fall 2010           Hungary      NaN
25   Fall 2010             India      7.0
26   Fall 2010         Indonesia      1.0
27   Fall 2010              Iran      1.0
28   Fall 2010              Iraq      2.0
29   Fall 2010           Ireland      4.0
..         ...               ...      ...
627  Fall 2018            Norway      2.0
628  Fall 2018       North Korea      NaN
629  Fall 2018          Pakistan     14.0
630  Fall 2018         Palestine      7.0
631  Fall 2018            Poland      3.0
632  Fall 2018          Portugal      1.0
633  Fall 2018           Romania      3.0
634  Fall 2018            Russia      3.0
635  Fall 2018      Saudi Arabia      4.0
636  Fall 2018            Serbia      1.0
637  Fall 2018         Singapore      4.0
638  Fall 2018          Slovenia      1.0
639  Fall 2018      South Africa      2.0
640  Fall 2018       South Korea      4.0
641  Fall 2018             Spain      2.0
642  Fall 2018             Sudan      3.0
643  Fall 2018            Sweden      2.0
644  Fall 2018       Switzerland      2.0
645  Fall 2018             Syria      9.0
646  Fall 2018          Tanzania      NaN
647  Fall 2018           Tunisia      3.0
648  Fall 2018            Turkey     12.0
649  Fall 2018             U S A    134.0
650  Fall 2018               UAE     71.0
651  Fall 2018                UK     80.0
652  Fall 2018        Uzbekistan      1.0
653  Fall 2018             Yemen      NaN
654  Fall 2018        Yugoslavia      1.0
655  Fall 2018          Zimbabwe      NaN
656  Fall 2018           (blank)      1.0

[657 rows x 3 columns]